# Generated by Django 4.2.11 on 2026-08-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_case_assigned_judge_case_public_interest_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CASE_FILED', 'Case Filed'), ('CASE_REGISTERED', 'Case Registered'), ('NOTICE_ISSUED', 'Notice Issued'), ('LAWYER_ASSIGNED', 'Lawyer Assigned'), ('HEARING_CREATED', 'Hearing Created'), ('HEARING_COMPLETED', 'Hearing Completed'), ('HEARING_ADJOURNED', 'Hearing Adjourned'), ('HEARING_RESCHEDULED', 'Hearing Rescheduled'), ('HEARING_CANCELLED', 'Hearing Cancelled'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('ORDER_CREATED', 'Order Created'), ('ORDER_PUBLISHED', 'Order Published'), ('STATUS_CHANGED', 'Status Changed'), ('CASE_TRANSFERRED', 'Case Transferred'), ('CASE_DISPOSED', 'Case Disposed'), ('PROCEEDING_RECORDED', 'Proceeding Recorded'), ('TASK_CREATED', 'Task Created'), ('TASK_COMPLETED', 'Task Completed'), ('OTHER', 'Other')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField(db_index=True)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('related_entity', models.CharField(blank=True, help_text='Human-readable target: Hearing #7, Order #2...', max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseLawyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('lead', 'Lead Counsel'), ('co_counsel', 'Co-Counsel'), ('associate', 'Associate'), ('assistant', 'Assistant')], default='associate', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_type', models.CharField(choices=[('petitioner', 'Petitioner'), ('respondent', 'Respondent'), ('applicant', 'Applicant'), ('opponent', 'Opponent'), ('intervenor', 'Intervenor'), ('third_party', 'Third Party')], db_index=True, max_length=30)),
                ('party_kind', models.CharField(choices=[('person', 'Person'), ('organization', 'Organization'), ('government', 'Government'), ('other', 'Other')], default='person', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('representation', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Expose minimal public info (name) to guests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['party_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CaseStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStatusOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_system', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='cnr_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='courts.court'),
        ),
        migrations.AddField(
            model_name='case',
            name='courtroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='courts.courtroom'),
        ),
        migrations.AddField(
            model_name='case',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='disposal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='disposal_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Public case information visible to guests'),
        ),
        migrations.AddField(
            model_name='case',
            name='priority',
            field=models.CharField(choices=[('URGENT', 'Urgent'), ('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low')], db_index=True, default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned_lawyer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'lawyer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='defendant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='next_hearing_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='plaintiff_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('FILED', 'Filed'), ('REGISTERED', 'Registered'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('ADJOURNED', 'Adjourned'), ('RESERVED_FOR_ORDER', 'Reserved for Order'), ('DISPOSED', 'Disposed'), ('TRANSFERRED', 'Transferred'), ('CLOSED', 'Closed')], db_index=True, default='FILED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['cnr_number'], name='cases_case_cnr_num_3874c4_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['court'], name='cases_case_court_i_ac502c_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['filing_date'], name='cases_case_filing__d5a33e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['next_hearing_date'], name='cases_case_next_he_30bbed_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_type'], name='cases_case_case_ty_2efb82_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority'], name='cases_case_priorit_474e7d_idx'),
        ),
        migrations.DeleteModel(
            name='CaseTimeline',
        ),
        migrations.AddField(
            model_name='casestatushistory',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casestatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseparty',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='cases.case'),
        ),
        migrations.AddField(
            model_name='caselawyer',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_lawyers', to='cases.case'),
        ),
        migrations.AddField(
            model_name='caselawyer',
            name='lawyer',
            field=models.ForeignKey(limit_choices_to={'role': 'lawyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='case_lawyer_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case'),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='casestatushistory',
            index=models.Index(fields=['case', 'created_at'], name='cases_cases_case_id_a7168e_idx'),
        ),
        migrations.AddIndex(
            model_name='caseparty',
            index=models.Index(fields=['case', 'party_type'], name='cases_casep_case_id_a7c6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='caselawyer',
            index=models.Index(fields=['lawyer', 'is_active'], name='cases_casel_lawyer__21fc8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caselawyer',
            unique_together={('case', 'lawyer')},
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['case', 'event_date'], name='cases_casee_case_id_f60e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['event_type'], name='cases_casee_event_t_94491b_idx'),
        ),
    ]
