# Generated by Django 4.2.11 on 2026-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="professional_id",
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("judge", "Judge"),
                    ("lawyer", "Lawyer"),
                    ("guest", "Guest"),
                ],
                default="lawyer",
                max_length=20,
            ),
        ),
    ]
