# Generated by Django 4.2.11 on 2026-05-31 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("documents", "0001_initial"),
        ("ai_assistant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentembedding",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embedding",
                to="documents.casedocument",
            ),
        ),
        migrations.AddField(
            model_name="aiquery",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_queries",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="aiquery",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="ai_assistant.aiconversation",
            ),
        ),
        migrations.AddField(
            model_name="aiconversation",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_conversations",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="aiconversation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
