# Generated by Django 4.2.11 on 2026-08-12 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('case', 'Case'), ('hearing', 'Hearing'), ('proceeding', 'Proceeding'), ('document', 'Document'), ('order', 'Order'), ('party', 'Party'), ('event', 'Timeline Event'), ('chunk', 'Document Chunk')], max_length=30)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('source_label', models.CharField(help_text='Human-readable label, e.g. Hearing #7 - 25 July 2026', max_length=255)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('chunk_index', models.PositiveIntegerField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='ai_assistant.aimessage')),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='ai_assistant.aiquery')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message'], name='ai_assistan_message_16f417_idx'), models.Index(fields=['source_type', 'source_id'], name='ai_assistan_source__d867ff_idx')],
            },
        ),
    ]
