# Generated by Django 4.2.11 on 2026-08-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0001_initial'),
        ('cases', '0003_caseevent_caselawyer_caseparty_casestatushistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjournmentReasonOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hearing_number', models.PositiveIntegerField(default=0, help_text='Sequential hearing number within the case')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('hearing_type', models.CharField(choices=[('FIRST', 'First Hearing'), ('ARGUMENTS', 'Arguments'), ('EVIDENCE', 'Evidence Recording'), ('ORDER', 'Order/Judgment'), ('INTERIM', 'Interim Application'), ('ADJOURNMENT', 'Adjournment'), ('OTHER', 'Other')], default='FIRST', max_length=50)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ADJOURNED', 'Adjourned'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('adjournment_note', models.TextField(blank=True)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('next_hearing_notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Public hearing date/time visible to guests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjournment_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearings', to='hearings.adjournmentreasonoption')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.case')),
                ('courtroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearings', to='courts.courtroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hearings', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(blank=True, limit_choices_to={'role': 'judge'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presided_hearings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='HearingProceeding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('submissions', models.TextField(blank=True)),
                ('directions', models.TextField(blank=True)),
                ('attendance', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceedings', to='hearings.hearing')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_proceedings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hearing'], name='hearings_he_hearing_2f9471_idx')],
            },
        ),
        migrations.CreateModel(
            name='HearingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Free-text name when no user account', max_length=255)),
                ('role', models.CharField(choices=[('judge', 'Judge'), ('lawyer', 'Lawyer'), ('petitioner', 'Petitioner'), ('respondent', 'Respondent'), ('witness', 'Witness'), ('court_staff', 'Court Staff'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('REPRESENTED', 'Represented'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='hearings.hearing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearing_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'name'],
                'indexes': [models.Index(fields=['hearing', 'role'], name='hearings_he_hearing_743d9d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['case', 'date'], name='hearings_he_case_id_a3e2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['date'], name='hearings_he_date_474da2_idx'),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['judge', 'date'], name='hearings_he_judge_i_60e803_idx'),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['status'], name='hearings_he_status_7ee3fd_idx'),
        ),
    ]
