# Generated by Django 4.2.11 on 2026-08-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_documentaccess_documentchunk_casedocument_checksum_and_more'),
        ('hearings', '0001_initial'),
        ('cases', '0003_caseevent_caselawyer_caseparty_casestatushistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('order_type', models.CharField(choices=[('INTERIM', 'Interim Order'), ('FINAL', 'Final Order'), ('JUDGMENT', 'Judgment'), ('DIRECTION', 'Direction'), ('ADJOURNMENT', 'Adjournment Order'), ('OTHER', 'Other')], default='INTERIM', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SIGNED', 'Signed'), ('PUBLISHED', 'Published'), ('SUPERSEDED', 'Superseded')], db_index=True, default='DRAFT', max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('LAWYER_ONLY', 'Lawyers Only'), ('JUDGE_ONLY', 'Judge Only'), ('RESTRICTED', 'Restricted'), ('ADMIN_ONLY', 'Admin Only')], default='LAWYER_ONLY', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Visible to guest/public users')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='documents.casedocument')),
                ('hearing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='hearings.hearing')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='orders.order')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('content_text', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_versions', to='documents.casedocument')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='orders.order')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('order', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['case', 'date'], name='orders_orde_case_id_f30643_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['date'], name='orders_orde_date_5ec531_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
    ]
