# Generated by Django 4.2.11 on 2026-08-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CASE_CREATED', 'Case Created'), ('CASE_UPDATED', 'Case Updated'), ('CASE_ASSIGNED', 'Case Assigned'), ('CASE_DELETED', 'Case Deleted'), ('CASE_STATUS_CHANGED', 'Case Status Changed'), ('HEARING_CREATED', 'Hearing Created'), ('HEARING_UPDATED', 'Hearing Updated'), ('HEARING_RESCHEDULED', 'Hearing Rescheduled'), ('HEARING_CANCELLED', 'Hearing Cancelled'), ('PROCEEDINGS_CREATED', 'Proceedings Created'), ('PROCEEDINGS_UPDATED', 'Proceedings Updated'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_VIEWED', 'Document Viewed'), ('DOCUMENT_DOWNLOADED', 'Document Downloaded'), ('DOCUMENT_DELETED', 'Document Deleted'), ('DOCUMENT_VERSION_CREATED', 'Document Version Created'), ('DOCUMENT_VISIBILITY_CHANGED', 'Document Visibility Changed'), ('ORDER_CREATED', 'Order Created'), ('ORDER_UPDATED', 'Order Updated'), ('ORDER_PUBLISHED', 'Order Published'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('PERMISSION_CHANGED', 'Permission Changed'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('CSV_IMPORT', 'CSV Import'), ('AI_QUERY', 'AI Query'), ('OTHER', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='audit_audit_model_n_20c0d3_idx'),
        ),
    ]
