# Generated by Django 4.2.11 on 2026-08-12 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_lawyerprofile_judgeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('totp', 'TOTP (authenticator app)'), ('webauthn', 'WebAuthn / Passkey'), ('sms', 'SMS OTP'), ('email', 'Email OTP')], default='totp', max_length=30)),
                ('secret_encrypted', models.TextField(blank=True, help_text='Provider secret (encrypted at rest)')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_enabled'], name='authenticat_user_id_0fa4a9_idx')],
            },
        ),
    ]
