# Generated by Django 4.2.11 on 2026-08-12 08:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_two_factor_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorWebAuthnCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('credential_id', models.TextField(help_text='Base64url credential ID')),
                ('public_key', models.TextField(help_text='Base64url COSE public key')),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('transports', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('two_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to='authentication.twofactorauth')),
            ],
            options={
                'indexes': [models.Index(fields=['two_factor'], name='authenticat_two_fac_4b9fe2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorRecoveryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('two_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to='authentication.twofactorauth')),
            ],
            options={
                'indexes': [models.Index(fields=['two_factor', 'used_at'], name='authenticat_two_fac_c26eef_idx')],
            },
        ),
    ]
