# Generated by Django 4.2.11 on 2026-08-12 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('court_type', models.CharField(choices=[('supreme', 'Supreme Court'), ('high', 'High Court'), ('district', 'District Court'), ('session', 'Sessions Court'), ('civil', 'Civil Court'), ('criminal', 'Criminal Court'), ('family', 'Family Court'), ('tribunal', 'Tribunal'), ('other', 'Other')], default='other', max_length=50)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Courtroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courtrooms', to='courts.court')),
            ],
            options={
                'ordering': ['court', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['court_type'], name='courts_cour_court_t_8b0134_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['state'], name='courts_cour_state_de8f8f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courtroom',
            unique_together={('court', 'name')},
        ),
    ]
