# Generated by Django 4.2.11 on 2026-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casedocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("petition", "Petition"),
                    ("affidavit", "Affidavit"),
                    ("judgment", "Judgment"),
                    ("order", "Order"),
                    ("evidence", "Evidence"),
                    ("statement", "Statement"),
                    ("bonafide", "Bonafide Document"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
