# Generated by Django 4.2.11 on 2026-08-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '__first__'),
        ('cases', '0003_caseevent_caselawyer_caseparty_casestatushistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_alter_casedocument_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('read', 'Read'), ('download', 'Download'), ('write', 'Write')], default='read', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('embedding', models.BinaryField(blank=True, help_text='Serialized pgvector embedding', null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=200)),
                ('document_version', models.PositiveIntegerField(default=1)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('LAWYER_ONLY', 'Lawyers Only'), ('JUDGE_ONLY', 'Judge Only'), ('RESTRICTED', 'Restricted'), ('ADMIN_ONLY', 'Admin Only')], default='LAWYER_ONLY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.AddField(
            model_name='casedocument',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 of the file', max_length=64),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='hearing',
            field=models.ForeignKey(blank=True, help_text='Hearing this document is associated with, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='hearings.hearing'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='mime_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='processing_state',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('OCR_REQUIRED', 'OCR Required'), ('OCR_COMPLETED', 'OCR Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=30),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('SUPERSEDED', 'Superseded'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='storage_key',
            field=models.CharField(blank=True, help_text='S3-compatible object key', max_length=500),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('LAWYER_ONLY', 'Lawyers Only'), ('JUDGE_ONLY', 'Judge Only'), ('RESTRICTED', 'Restricted'), ('ADMIN_ONLY', 'Admin Only')], db_index=True, default='LAWYER_ONLY', max_length=20),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='page_metadata',
            field=models.JSONField(default=dict, help_text='Per-page text/OCR info'),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='document_type',
            field=models.CharField(choices=[('petition', 'Petition'), ('reply', 'Reply'), ('affidavit', 'Affidavit'), ('evidence', 'Evidence'), ('written_submission', 'Written Submission'), ('order', 'Order'), ('judgment', 'Judgment'), ('proceedings', 'Proceedings'), ('annexure', 'Annexure'), ('statement', 'Statement'), ('bonafide', 'Bonafide Document'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['case', 'hearing'], name='documents_c_case_id_5f5197_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['visibility'], name='documents_c_visibil_2cc75e_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['processing_state'], name='documents_c_process_8220ea_idx'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='cases.case'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.casedocument'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='hearing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_chunks', to='hearings.hearing'),
        ),
        migrations.AddField(
            model_name='documentaccess',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='documents.casedocument'),
        ),
        migrations.AddField(
            model_name='documentaccess',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_doc_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='documents_d_documen_8ea6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['case'], name='documents_d_case_id_b0b392_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['page_number'], name='documents_d_page_nu_2ab6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccess',
            index=models.Index(fields=['user', 'access_level'], name='documents_d_user_id_069a83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentaccess',
            unique_together={('document', 'user')},
        ),
    ]
