# Generated by Django 4.2.11 on 2026-08-12 07:34

from django.db import migrations, models
import pgvector.django.vector


def create_vector_extension(apps, schema_editor):
    """pgvector is a PostgreSQL feature and must not run against SQLite tests."""
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('CREATE EXTENSION IF NOT EXISTS vector;')


def drop_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP EXTENSION IF EXISTS vector;')


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentaccess_documentchunk_casedocument_checksum_and_more'),
    ]

    operations = [
        # pgvector extension must exist before the vector column is created.
        # (PostgreSQL only; the app requires PostgreSQL for vector features.)
        migrations.RunPython(create_vector_extension, drop_vector_extension),
        # 0003 created the column as bytea (BinaryField). Replace it with a
        # real pgvector column (drop + recreate; no legacy data to preserve).
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedding',
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=768, help_text='pgvector embedding (768-dim)', null=True,
            ),
        ),
    ]
