# Generated by Django 4.2.11 on 2026-08-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documentchunk_embedding_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='collection',
            field=models.CharField(db_index=True, default='case_documents', max_length=100),
        ),
    ]
