# Generated by Django 4.2.11 on 2026-07-05 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="assigned_judge",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "judge"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="judged_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="public_interest_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["assigned_judge"], name="cases_case_assigne_213b54_idx"
            ),
        ),
    ]
