# Generated by Django 4.2.11 on 2026-08-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_documentaccess_documentchunk_casedocument_checksum_and_more'),
        ('hearings', '0001_initial'),
        ('cases', '0003_caseevent_caselawyer_caseparty_casestatushistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('URGENT', 'Urgent'), ('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low')], db_index=True, default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], db_index=True, default='TODO', max_length=20)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='documents.casedocument')),
                ('hearing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='hearings.hearing')),
            ],
            options={
                'ordering': ['-priority', 'due_date', 'created_at'],
                'indexes': [models.Index(fields=['assigned_to', 'status'], name='tasks_task_assigne_b3b2bc_idx'), models.Index(fields=['assigned_to', 'due_date'], name='tasks_task_assigne_da4339_idx'), models.Index(fields=['case'], name='tasks_task_case_id_29e236_idx')],
            },
        ),
    ]
